export const GET_LOCATION_FROM_API = "GET_LOCATION_FROM_API";
export const UPDATE_ARRAY_BY_SEARCHING = "UPDATE_ARRAY_BY_SEARCHING";
export const UPDATE_ARRAY_BY_FILTERING = "UPDATE_ARRAY_BY_FILTERING";
export const START_LOGIN = "START_LOGIN";
export const END_LOGIN = "END_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const START_SIGNUP = "START_SIGNUP";
export const END_SIGNUP = "END_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// delete location
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";
export const DELETE_LOCATION_END = "DELETE_LOCATION_END";

// update location
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";
export const UPDATE_LOCATION_END = "UPDATE_LOCATION_END";

// create location
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";
export const CREATE_LOCATION_END = "CREATE_LOCATION_END";
