export const GET_LOCATION_FROM_API = "GET_LOCATION_FROM_API";
export const GET_LOCATION_DETAIL_API = "GET_LOCATION_DETAIL_API";
export const CLEAR_LOCATION_DETAIL = "CLEAR_LOCATION_DETAIL";

export const UPDATE_ARRAY_BY_SEARCHING = "UPDATE_ARRAY_BY_SEARCHING";
export const UPDATE_ARRAY_BY_FILTERING = "UPDATE_ARRAY_BY_FILTERING";
export const START_LOGIN = "START_LOGIN";
export const END_LOGIN = "END_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const START_SIGNUP = "START_SIGNUP";
export const END_SIGNUP = "END_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// delete location
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";
export const DELETE_LOCATION_END = "DELETE_LOCATION_END";

// update location
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";
export const UPDATE_LOCATION_END = "UPDATE_LOCATION_END";

// create location
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";
export const CREATE_LOCATION_END = "CREATE_LOCATION_END";

//
export const GET_USER = "GET_USER";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const CLEAR_USER_DETAIL = "CLEAR_USER_DETAIL";

// update user
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_END = "UPDATE_USER_END";

// delete user
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_END = "DELETE_USER_END";

// create user
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_END = "CREATE_USER_END";

// update user avatar
export const UPDATE_USER_AVATAR_SUCCESS = "UPDATE_USER_AVATAR_SUCCESS";
export const UPDATE_USER_AVATAR_FAIL = "UPDATE_USER_AVATAR_FAIL";
export const UPDATE_USER_AVATAR_END = "UPDATE_USER_AVATAR_END";

// get rooms
export const GET_ROOM_BY_LOCATION = "GET_ROOM_BY_LOCATION";
export const UPDATE_ROOM_LIST_BY_SEARCHING_AND_FILTERING = "UPDATE_ROOM_LIST_BY_SEARCHING_AND_FILTERING";
export const GET_ROOM_DETAIL = "GET_ROOM_DETAIL";
export const CLEAR_ROOM_DETAIL = "CLEAR_ROOM_DETAIL";
export const CLEAR_ROOM_LIST = "CLEAR_ROOM_LIST";

// update room
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAIL = "UPDATE_ROOM_FAIL";
export const UPDATE_ROOM_END = "UPDATE_ROOM_END";

// upload image room
export const UPLOAD_IMAGE_ROOM_SUCCESS = "UPLOAD_IMAGE_ROOM_SUCCESS";
export const UPLOAD_IMAGE_ROOM_FAIL = "UPLOAD_IMAGE_ROOM_FAIL";
export const UPLOAD_IMAGE_ROOM_END = "UPLOAD_IMAGE_ROOM_END";

// delete room
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAIL = "DELETE_ROOM_FAIL";
export const DELETE_ROOM_END = "DELETE_ROOM_END";

// create room
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL";
export const CREATE_ROOM_END = "CREATE_ROOM_END";

// create review
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_END = "CREATE_REVIEW_END";

// get review
export const GET_REVIEW_BY_ROOM = "GET_REVIEW_BY_ROOM";
export const CLEAR_REVIEW_LIST = "CLEAR_REVIEW_LIST";

// delete review
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_END = "DELETE_REVIEW_END";

// create ticket
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";
export const CREATE_TICKET_END = "CREATE_TICKET_END";
